### ISSUE TITLE
503 error

### ISSUE THREAD

**Issue by mgaulton** [mattes/rotating-proxy#13]
running as the pulled container, i'm getting a consistent 503 error and i'm not sure why. i've repulled multitple times and all the usual. the logs look find to me. Looking for suggestions on troubleshooting this. 

server6:~ # curl --proxy torprox.docker:5566 http://www.google.ca
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>

**Comment by mgaulton** [comment]
Aaaaand i think fixed it by deleting the pid files in /var/run/polipo after seeing messages that the pids couldn't be written. not sure if its permanent, but it appears to be working at the moment.

**Comment by Mehonoshin** [comment]
Having the same issue.
I see the following in the logs:
`Couldn't create pid file /var/run/polipo/20000.pid: File exists`

**Comment by mattes** [comment]
I guess this TOR network related. Closing this for now. Feel free to re-open if problem persists.

**Comment by joanas2azz** [comment]
Hi

root@gmk:~# curl --proxy xx.xx.xx.xx:4444 http://api.ipify.org?format=json
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>

Same problem
