### ISSUE TITLE
new to docker

### ISSUE THREAD

**Issue by chovy** [mattes/rotating-proxy#17]
Can you provide instructions on how to setup docker?

Do I install docker on the server (ubuntu) and then run these commands?

**Comment by Mehonoshin** [comment]
@chovy hi!
I suppose that describing of docker installation is not the purpose of this projects documentation.
Check it out https://docs.docker.com/engine/installation/

To run this project you just should:

```
docker run -d -p 5566:5566 -p 1936:1936 --env tors=25 mattes/rotating-proxy
```

And use proxy available via port 5566.

**Comment by chovy** [comment]
I figured as much. Just would be nice to have a link to that in the docs.

I did go through their install but apparently my VPS is incapable of running docker:
https://github.com/docker/docker/issues/27376
