### ISSUE TITLE
Tor circus is slow

### ISSUE THREAD

**Issue by georgi-staykov** [mattes/rotating-proxy#18]
First of all thank you for the amazing project. Great work !

I have noticed that most of the requests are processed very more slowly than others (some times they are very slow > 1 minute). As I understand the speed of request processing depends on the number of tors that I'm using. But in other hand more tors result in better security (traffic obfuscation). What is the best ratio for speed/security (speed/tors number) ? Also in my understanding the tor circus is using local computer resources ( CPU and RAM ) to obfuscate the traffic. Does this mean that if I have more computing power the requests will be processed faster ?

**Comment by mattes** [comment]
I'm pretty sure it's TOR, not your machine.
