### ISSUE TITLE
curl: (56) Recv failure: Connection reset by peer

### ISSUE THREAD

**Issue by omin** [mattes/rotating-proxy#20]
I get `curl: (56) Recv failure: Connection reset by peer` or `curl: (56) Proxy CONNECT aborted
`errors when I increase the number of tors to be greater than 25.

**Comment by mattes** [comment]
You can monitor (http://xxxxxx:4444/haproxy?stats) and see what might be causing this. It's most likely TOR itself.

**Comment by mattes** [comment]
dup #3
