### ISSUE TITLE
No response returned

### ISSUE THREAD

**Issue by MPJHorner** [mattes/rotating-proxy#22]
Stats are showing traffic in/out see http://prntscr.com/eyfw9q (on both attached/detached) however it doesn't return response (it seems) to haproxy.

I get a response (assume after timeout) of 

```
<html><body><h1>502 Bad Gateway</h1>
The server returned an invalid or incomplete response.
</body></html>
```

This is exactly what i'm after and looks like an excellent dockerfile just seems to need patching upto date or im being stupid?

**Comment by mattes** [comment]
It might just be TOR. Is it returning `502` for all request?

**Comment by MPJHorner** [comment]
Yeh, all requests and they all take the same response time so I assume it not passing it back?

**Comment by mattes** [comment]
I just checked with the `latest` docker image. It seems to be working here.

**Comment by mattes** [comment]
Try `curl --proxy 127.0.0.1:5566 http://header.jsontest.com` and see if that returns anything.

**Comment by mattes** [comment]
possible related to #21

**Comment by MPJHorner** [comment]
#21 subsequent requests work after the initial. Here is my docker log output (with a couple of requests sent) https://pastebin.com/aRsbkCKb 

Just to clarify, I am using docker for mac (17.03.1-ce-mac5)

Thanks for getting back to me so promptly!

**Comment by MPJHorner** [comment]
Oddly, tried it on my ubuntu box and it worked (after cycling through 25 once each, thus first request per each tor node fails).

**Comment by MPJHorner** [comment]
Restart docker on my Mac, now working fine (including first time). Strange!

**Comment by mattes** [comment]
I'm glad it's working now. Please keep me updated if you find out more.
