### ISSUE TITLE
error after update

### ISSUE THREAD

**Issue by TheXeon81** [mattes/rotating-proxy#30]
hello to all!
i have installed rotating-proxy from many months an works.

yesterday there are an update of docker and now i'm at version 2.1.0.0 (36873) channel edge.
after this update  rotating-proxy not work! :-(

you can help me please?

**Comment by TheXeon81** [comment]
![image](https://user-images.githubusercontent.com/5238466/62429782-4025ee00-b713-11e9-92c9-7e1d504be32f.png)

**Comment by TheXeon81** [comment]
![image](https://user-images.githubusercontent.com/5238466/62429801-7c594e80-b713-11e9-8925-2743a8900c2f.png)

**Comment by TheXeon81** [comment]
consolle 

![image](https://user-images.githubusercontent.com/5238466/62429807-9abf4a00-b713-11e9-8855-99e807a9d99e.png)

**Comment by mattes** [comment]
needs more info. seems to work for me. closing for now.
