### ISSUE TITLE
Is there anyway to renew tor ip? after a bit of time?

### ISSUE THREAD

**Issue by Ammadkhalid** [mattes/rotating-proxy#33]
I wonder, if this is possible? like i wanted to use fresh IP every 1-3 hours but with limit of 5 tors. Until this much hours, IP may get blacklist

**Comment by Ammadkhalid** [comment]
i think it can change by tor automatically in 10 seconds?
```
CircuitBuildTimeout 10
LearnCircuitBuildTimeout 0
MaxCircuitDirtiness 10
```

https://www.reddit.com/r/TOR/comments/81xjk7/change_ipaddress_automatically_in_your_interval/

**Comment by aleksas** [comment]
If I unrestand correctly, these are passed: https://github.com/mattes/rotating-proxy/blob/master/start.rb#L103-L106
